//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Resources.Models.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GoodsAddViewModel_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoodsAddViewModel_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineStore.Resources.Models.ViewModels.ProductAddViewModel.ru-RU", typeof(GoodsAddViewModel_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер категории.
        /// </summary>
        internal static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата добавления.
        /// </summary>
        internal static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное описание (на русском).
        /// </summary>
        internal static string DescriptionFullEN {
            get {
                return ResourceManager.GetString("DescriptionFullEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное описание (на английском).
        /// </summary>
        internal static string DescriptionFullRU {
            get {
                return ResourceManager.GetString("DescriptionFullRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное описание (на украинском).
        /// </summary>
        internal static string DescriptionFullUA {
            get {
                return ResourceManager.GetString("DescriptionFullUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткое описание (на английском).
        /// </summary>
        internal static string DescriptionShortEN {
            get {
                return ResourceManager.GetString("DescriptionShortEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткое описание (на русском).
        /// </summary>
        internal static string DescriptionShortRU {
            get {
                return ResourceManager.GetString("DescriptionShortRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткое описание (на украинском).
        /// </summary>
        internal static string DescriptionShortUA {
            get {
                return ResourceManager.GetString("DescriptionShortUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (на английском).
        /// </summary>
        internal static string NameEN {
            get {
                return ResourceManager.GetString("NameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите название продукта..
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (на русском).
        /// </summary>
        internal static string NameRU {
            get {
                return ResourceManager.GetString("NameRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (на украинском).
        /// </summary>
        internal static string NameUA {
            get {
                return ResourceManager.GetString("NameUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите цену продукта..
        /// </summary>
        internal static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
    }
}
