//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Resources.Models.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductViewModel_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductViewModel_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineStore.Resources.Models.ViewModels.ProductViewModel.en-US", typeof(ProductViewModel_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID.
        /// </summary>
        internal static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date added.
        /// </summary>
        internal static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full description (English).
        /// </summary>
        internal static string DescriptionFullEN {
            get {
                return ResourceManager.GetString("DescriptionFullEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full description (Russian).
        /// </summary>
        internal static string DescriptionFullRU {
            get {
                return ResourceManager.GetString("DescriptionFullRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full description (Ukrainian).
        /// </summary>
        internal static string DescriptionFullUA {
            get {
                return ResourceManager.GetString("DescriptionFullUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description (English).
        /// </summary>
        internal static string DescriptionShortEN {
            get {
                return ResourceManager.GetString("DescriptionShortEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description (Russian).
        /// </summary>
        internal static string DescriptionShortRU {
            get {
                return ResourceManager.GetString("DescriptionShortRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description (Ukrainian).
        /// </summary>
        internal static string DescriptionShortUA {
            get {
                return ResourceManager.GetString("DescriptionShortUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        internal static string NameEN {
            get {
                return ResourceManager.GetString("NameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a name of product..
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Russian).
        /// </summary>
        internal static string NameRU {
            get {
                return ResourceManager.GetString("NameRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Ukrainian).
        /// </summary>
        internal static string NameUA {
            get {
                return ResourceManager.GetString("NameUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a price of product..
        /// </summary>
        internal static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
    }
}
